### ISSUE TITLE
안녕하세요 AttributeError: 'NoneType' object has no attribute 'dtype' 질문드립니다. 

### ISSUE THREAD

**Issue by easyseop** [ukairia777/finance_sentiment_corpus#1]
마지막 학습단계에서 AttributeError: 'NoneType' object has no attribute 'dtype' 오류가 발생하는데 찾아봐도 오류를 개선하는 법이 나와있지 않아서요 .. 버전 문제인가 생각중인데 혹시 해당 분석에 사용된 텐서플로우 버전 알 수 있을까요?

**Comment by ukairia777** [comment]
loss를 tf.keras.losses.SparseCategoricalCrossentropy()로 바꿔보시겠어요?

loss = model.compute_loss 이렇게 하지마시고
loss = tf.keras.losses.SparseCategoricalCrossentropy() 이렇게 해보세요
